# About TC
# - TCP SYN Handshaking process
#   - Client option
#     - SACK perem on, mss = 1460
#   - Server option
#     - SACK perem on, mss = 1460

[TC-information]
	creator = "Dry8r3aD <me@dry8r3ad.com>"
	name = "tcp_open_con_01"
	
	[TC-information.options]
    	use_auto_seq = "false"
    	use_fixed_win_size = 0

[client]
	interface = "en0"
	ip = "1.2.3.4"
	port = 4567

	[[client.packet]]
    	action = "send"
		seq = 1001
		ack = 1
		flags = [ "syn" ]
		
		[client.packet.option]
			mss = 1460
			sack_perm = "true"

	[[client.packet]]
    	action = "recv"
		seq = 1
		ack = 1002
		flags = [ "syn", "ack" ]
		
		[client.packet.option]
			mss = 1460
			sack_perm = "true"

	[[client.packet]]
    	action = "recv"
		seq = 1
		ack = 1002
		flags = [ "ack" ]

[server]
	interface = "en1"
	ip = "1.2.3.5"
	port = 80

	[[server.packet]]
		actoin = "recv"
		seq = 1001
		ack = 1
		flags = [ "syn" ]

		[server.packet.option]
			mss = 1460
			sack_perm = "true"

	[[server.packet]]
		action = "send"
		seq = 1
		ack = 1002
		flags = [ "syn", "ack" ]
		
		[client.packet.option]
			mss = 1460
			sack_perm = "true"

	[[server.packet]]
	    action = "recv"
		seq = 1
		ack = 1002
		flags = [ "ack" ]
