# About TC
# - TCP SYN Handshaking process
#   - Client option
#     - SACK perem on, mss = 1460
#   - Server option
#     - SACK perem on, mss = 1460

[TC-information]
	creator = "Dry8r3aD <me@dry8r3ad.com>"
	name = "tcp_open_con_01"

	[TC-information.options]
    	use_auto_seq = "false"
    	use_fixed_win_size = 0

[PacketList]
	interface = "eth0" 	# Interface where we'll xmit the packet

	src_ip = "172.24.18.134"	# IP of mine
	dst_ip = "172.24.18.134"		# IP of the DUT

	src_port = 28509	# Port of mine
	dst_port = 5000		# Port of the DUT

	[[PacketList.packet]]
    	action = "send"
		seq = 1001
		flags = [ "syn" ]

		[PacketList.packet.option]
			mss = 1460
			sack_perm = "true"

	[[PacketList.packet]]
    	action = "recv"
		seq = 1
		ack = 1002
		flags = [ "syn", "ack" ]

		[PacketList.packet.option]
			mss = 1460
			sack_perm = "true"

	[[PacketList.packet]]
    	action = "send"
		seq = 1002
		ack = 2
		flags = [ "ack" ]
