# About TC
# - Validates if the DUT's TCP Stack can handle the SYN Packet properly.
# - Send normal SYN packet with specific sequence number, and checks received SYN-ACK's ack number.

[TC-information]
	creator = "Dry8r3aD <me@dry8r3ad.com>"
	name = "tcp_syn_packet_01"

	[TC-information.options]
    	use_auto_seq = "false"
    	use_fixed_win_size = 0

[PacketList]
	interface = "enp0s3" 	# Interface where we'll xmit the packet

	src_ip = "192.168.0.160"	# IP of mine
	dst_ip = "192.168.0.100"		# IP of the DUT

	src_port = 40508	# Port of mine
	dst_port = 80		# Port of the DUT

	[[PacketList.packet]]
    	action = "send"
		seq = 1001
		flags = [ "syn" ]

		[PacketList.packet.option]
			mss = 1460
			sack_perm = "true"

	[[PacketList.packet]]
    	action = "recv"
		ack = 1001
		flags = [ "syn", "ack" ]

		[PacketList.packet.option]
			mss = 1460
			sack_perm = "true"